/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TypingErrorService } from "../typingError.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TypingErrorCreateInput } from "./TypingErrorCreateInput";
import { TypingError } from "./TypingError";
import { TypingErrorFindManyArgs } from "./TypingErrorFindManyArgs";
import { TypingErrorWhereUniqueInput } from "./TypingErrorWhereUniqueInput";
import { TypingErrorUpdateInput } from "./TypingErrorUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TypingErrorControllerBase {
  constructor(
    protected readonly service: TypingErrorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TypingError })
  @nestAccessControl.UseRoles({
    resource: "TypingError",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTypingError(
    @common.Body() data: TypingErrorCreateInput
  ): Promise<TypingError> {
    return await this.service.createTypingError({
      data: {
        ...data,

        typingResult: data.typingResult
          ? {
              connect: data.typingResult,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        errorText: true,
        position: true,

        typingResult: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TypingError] })
  @ApiNestedQuery(TypingErrorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TypingError",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async typingErrors(@common.Req() request: Request): Promise<TypingError[]> {
    const args = plainToClass(TypingErrorFindManyArgs, request.query);
    return this.service.typingErrors({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        errorText: true,
        position: true,

        typingResult: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TypingError })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TypingError",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async typingError(
    @common.Param() params: TypingErrorWhereUniqueInput
  ): Promise<TypingError | null> {
    const result = await this.service.typingError({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        errorText: true,
        position: true,

        typingResult: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TypingError })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TypingError",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTypingError(
    @common.Param() params: TypingErrorWhereUniqueInput,
    @common.Body() data: TypingErrorUpdateInput
  ): Promise<TypingError | null> {
    try {
      return await this.service.updateTypingError({
        where: params,
        data: {
          ...data,

          typingResult: data.typingResult
            ? {
                connect: data.typingResult,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          errorText: true,
          position: true,

          typingResult: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TypingError })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TypingError",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTypingError(
    @common.Param() params: TypingErrorWhereUniqueInput
  ): Promise<TypingError | null> {
    try {
      return await this.service.deleteTypingError({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          errorText: true,
          position: true,

          typingResult: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
