/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TypingResultService } from "../typingResult.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TypingResultCreateInput } from "./TypingResultCreateInput";
import { TypingResult } from "./TypingResult";
import { TypingResultFindManyArgs } from "./TypingResultFindManyArgs";
import { TypingResultWhereUniqueInput } from "./TypingResultWhereUniqueInput";
import { TypingResultUpdateInput } from "./TypingResultUpdateInput";
import { TypingErrorFindManyArgs } from "../../typingError/base/TypingErrorFindManyArgs";
import { TypingError } from "../../typingError/base/TypingError";
import { TypingErrorWhereUniqueInput } from "../../typingError/base/TypingErrorWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TypingResultControllerBase {
  constructor(
    protected readonly service: TypingResultService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TypingResult })
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTypingResult(
    @common.Body() data: TypingResultCreateInput
  ): Promise<TypingResult> {
    return await this.service.createTypingResult({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        typingTest: data.typingTest
          ? {
              connect: data.typingTest,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        wordsPerMinute: true,
        accuracy: true,

        user: {
          select: {
            id: true,
          },
        },

        typingTest: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TypingResult] })
  @ApiNestedQuery(TypingResultFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async typingResults(@common.Req() request: Request): Promise<TypingResult[]> {
    const args = plainToClass(TypingResultFindManyArgs, request.query);
    return this.service.typingResults({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        wordsPerMinute: true,
        accuracy: true,

        user: {
          select: {
            id: true,
          },
        },

        typingTest: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TypingResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async typingResult(
    @common.Param() params: TypingResultWhereUniqueInput
  ): Promise<TypingResult | null> {
    const result = await this.service.typingResult({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        wordsPerMinute: true,
        accuracy: true,

        user: {
          select: {
            id: true,
          },
        },

        typingTest: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TypingResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTypingResult(
    @common.Param() params: TypingResultWhereUniqueInput,
    @common.Body() data: TypingResultUpdateInput
  ): Promise<TypingResult | null> {
    try {
      return await this.service.updateTypingResult({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          typingTest: data.typingTest
            ? {
                connect: data.typingTest,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          wordsPerMinute: true,
          accuracy: true,

          user: {
            select: {
              id: true,
            },
          },

          typingTest: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TypingResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTypingResult(
    @common.Param() params: TypingResultWhereUniqueInput
  ): Promise<TypingResult | null> {
    try {
      return await this.service.deleteTypingResult({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          wordsPerMinute: true,
          accuracy: true,

          user: {
            select: {
              id: true,
            },
          },

          typingTest: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/typingErrors")
  @ApiNestedQuery(TypingErrorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TypingError",
    action: "read",
    possession: "any",
  })
  async findTypingErrors(
    @common.Req() request: Request,
    @common.Param() params: TypingResultWhereUniqueInput
  ): Promise<TypingError[]> {
    const query = plainToClass(TypingErrorFindManyArgs, request.query);
    const results = await this.service.findTypingErrors(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        errorText: true,
        position: true,

        typingResult: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/typingErrors")
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "update",
    possession: "any",
  })
  async connectTypingErrors(
    @common.Param() params: TypingResultWhereUniqueInput,
    @common.Body() body: TypingErrorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      typingErrors: {
        connect: body,
      },
    };
    await this.service.updateTypingResult({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/typingErrors")
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "update",
    possession: "any",
  })
  async updateTypingErrors(
    @common.Param() params: TypingResultWhereUniqueInput,
    @common.Body() body: TypingErrorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      typingErrors: {
        set: body,
      },
    };
    await this.service.updateTypingResult({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/typingErrors")
  @nestAccessControl.UseRoles({
    resource: "TypingResult",
    action: "update",
    possession: "any",
  })
  async disconnectTypingErrors(
    @common.Param() params: TypingResultWhereUniqueInput,
    @common.Body() body: TypingErrorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      typingErrors: {
        disconnect: body,
      },
    };
    await this.service.updateTypingResult({
      where: params,
      data,
      select: { id: true },
    });
  }
}
